# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- deployment.yaml
- service.yaml

# namespace to deploy all Resources to
namespace: ss3d-server-browser

# labels added to all Resources
commonLabels:
  app: ss3d-server-browser