version: '3'

services:
           
  rabbitmq:
    build: rabbitmq
    labels:
      kompose.service.type: nodeport
    ports:
      - "5672:5672"
      - '15672:15672'
  
  gateway:
    build:
      context: ./
      dockerfile: ./Dockerfile-Gateway
    image: millybits/ss3d-server-browser-gateway
    ports:
      - '5000:5000'
      
  servers-microservice:
    build:
      context: ./
      dockerfile: ./Dockerfile-Servers
    image: millybits/ss3d-server-browser-servers-microservice
    ports:
      - '8050:8080'
    restart: unless-stopped
      
  servers-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servers
    ports:
      - 3306:3306
    expose: 
      - '3306'
    volumes:
      - servers-db:/var/lib/mysql
      
  news-microservice:
    build:
      context: ./
      dockerfile: ./Dockerfile-News
    image: millybits/ss3d-server-browser-news-microservice
    ports:
      - '8060:8080'
    restart: unless-stopped
    
  servers-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    ports:
      - 3306:3306
    expose: 
      - '3306'
    volumes:
      - news-db:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8091:8080
        
volumes:
  servers-db:
  news-db:
  