version: '3'

services:
           
  rabbitmq:
    build: rabbitmq
    labels:
      kompose.service.type: nodeport
    ports:
      - "5672:5672"
      - '15672:15672'
    volumes:
      - 'rabbitmq-data:/bitnami'
  
  gateway:
    build:
      context: ./
      dockerfile: ./Dockerfile-Gateway
    image: millybits/ss3d-server-browser-gateway
    ports:
      - '5000:5000'
      
  microservice-servers:
    build:
      context: ./
      dockerfile: ./Dockerfile-Servers
    image: millybits/ss3d-server-browser-servers-microservice
    ports:
      - '8050:8080'
    restart: always
      
  microservice-news:
    build:
      context: ./
      dockerfile: ./Dockerfile-News
    image: millybits/ss3d-server-browser-news-microservice
    ports:
      - '8060:8080'
    restart: always

  db-servers:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servers
    ports:
      - 3306:3306
    volumes:
      - db-servers:/var/lib/mysql

  db-news:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    cap_add:
    - SYS_NICE # CAP_SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - db-news:/var/lib/mysql
            
volumes:
  db-servers:
  db-news:
  rabbitmq-data:
      driver: local
  