name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      
    - name: Build docker-compose
      run: docker-compose build
    
    - name: Push docker-compose
      run: docker-compose push
  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      
    - name: Deploy new kubernetes deployment
      run: kubectl apply -k ./kubernetes
